name: Node.js Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
  build:
    runs-on: ubuntu-latest
    name: Check build and format have been run
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install
      - run: npm run format
      - run: npm run build
      - name: Fail if files changed
        run: |
          if [[ `git status --porcelain` ]]; then
            git status --porcelain
            git diff
            exit 1
          else
            exit 0
          fi
